"""
ELECTRA-style cooperative pre-training for the KG encoder.

A small generator (4-layer SciBERT) and a full discriminator (12-layer SciBERT)
share word + position embeddings. The generator fills [MASK] positions (MLM),
and the discriminator detects which tokens were replaced (RTD). Both are trained
cooperatively (MLE), NOT adversarially.

After pre-training, the discriminator weights are loaded into BertKGExtractor
for fine-tuning on labeled NER+RE data (train_span.py --pretrain-ckpt).

Usage:
    uv run python train_pretrain_cooperative.py --max-steps 100   # smoke test
    uv run python train_pretrain_cooperative.py --max-steps 10000  # full run
"""
import argparse
import json
import random
import time
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.optim import AdamW
from transformers import AutoTokenizer, get_linear_schedule_with_warmup

from models.bert_kg_encoder import BertKGExtractor
from models.electra_generator import SciBERTGenerator, ReplacedTokenDetector
from data.arxiv_real import build_arxiv_loader, cycle


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--model-name", default="allenai/scibert_scivocab_uncased")
    p.add_argument("--gen-layers", type=int, default=4)
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--max-length", type=int, default=128)
    p.add_argument("--mask-prob", type=float, default=0.15)
    p.add_argument("--span-mask", action="store_true",
                   help="Use span-level masking (TKRE-style) instead of token-level. "
                        "Masks contiguous spans of 2-5 tokens.")
    p.add_argument("--entity-mask-jsonl", default="",
                   help="JSONL with entity_token_mask for entity-aware masking. "
                        "Generated by generate_entity_masks.py.")
    p.add_argument("--entity-mask-prob", type=float, default=0.30,
                   help="Mask probability for entity tokens (default 0.30).")
    p.add_argument("--non-entity-mask-prob", type=float, default=0.10,
                   help="Mask probability for non-entity tokens (default 0.10).")
    p.add_argument("--lambda-disc", type=float, default=50.0,
                   help="Weight for discriminator RTD loss. ELECTRA default=50.")
    p.add_argument("--gen-lr", type=float, default=5e-4)
    p.add_argument("--disc-lr", type=float, default=5e-5)
    p.add_argument("--weight-decay", type=float, default=0.01)
    p.add_argument("--warmup-steps", type=int, default=500)
    p.add_argument("--max-steps", type=int, default=10000)
    p.add_argument("--eval-every", type=int, default=500)
    p.add_argument("--save-to", default="checkpoints/electra_pretrain.pt")
    p.add_argument("--device", default=None)
    p.add_argument("--seed", type=int, default=42)
    return p.parse_args()


def mask_tokens(input_ids, attention_mask, tokenizer, mask_prob=0.15):
    """
    ELECTRA-style token-level masking: randomly select mask_prob of
    non-special tokens and replace them with [MASK].

    Returns:
        masked_ids: (B, T) with [MASK] at selected positions
        mask_pos:   (B, T) bool — True where masking was applied
        orig_ids:   (B, T) original token ids (targets for MLM)
    """
    orig_ids = input_ids.clone()
    prob_matrix = torch.full(input_ids.shape, mask_prob, device=input_ids.device)

    # Don't mask special tokens or padding
    special = (
        (input_ids == tokenizer.cls_token_id) |
        (input_ids == tokenizer.sep_token_id) |
        (input_ids == tokenizer.pad_token_id)
    )
    prob_matrix.masked_fill_(special, 0.0)
    prob_matrix.masked_fill_(~attention_mask.bool(), 0.0)

    mask_pos = torch.bernoulli(prob_matrix).bool()
    masked_ids = input_ids.clone()
    masked_ids[mask_pos] = tokenizer.mask_token_id

    return masked_ids, mask_pos, orig_ids


def mask_tokens_span(input_ids, attention_mask, tokenizer, mask_prob=0.15,
                     span_len_min=2, span_len_max=5):
    """
    TKRE-style span-level masking: mask contiguous spans of 2-5 tokens
    until ~mask_prob of valid tokens are masked. Produces span-coherent
    signal better suited for downstream span NER.

    Reference: TKRE (IJCAI 2025) — Masked Span Language Modeling.

    Returns: same as mask_tokens.
    """
    B, T = input_ids.shape
    orig_ids = input_ids.clone()
    mask_pos = torch.zeros_like(input_ids, dtype=torch.bool)

    special = (
        (input_ids == tokenizer.cls_token_id) |
        (input_ids == tokenizer.sep_token_id) |
        (input_ids == tokenizer.pad_token_id)
    )
    valid = attention_mask.bool() & ~special  # (B, T)

    for b in range(B):
        valid_indices = valid[b].nonzero(as_tuple=True)[0]
        n_valid = len(valid_indices)
        if n_valid == 0:
            continue
        target_masked = int(n_valid * mask_prob)
        n_masked = 0

        # Randomly pick span starts and lengths until budget is met
        attempts = 0
        while n_masked < target_masked and attempts < n_valid:
            span_len = random.randint(span_len_min, span_len_max)
            # Pick a random start from valid positions
            start_idx = random.randint(0, n_valid - 1)
            start_pos = valid_indices[start_idx].item()

            for offset in range(span_len):
                pos = start_pos + offset
                if pos >= T:
                    break
                if special[b, pos]:
                    break
                if not attention_mask[b, pos]:
                    break
                if not mask_pos[b, pos]:
                    mask_pos[b, pos] = True
                    n_masked += 1
            attempts += 1

    masked_ids = input_ids.clone()
    masked_ids[mask_pos] = tokenizer.mask_token_id

    return masked_ids, mask_pos, orig_ids


def mask_tokens_entity_aware(input_ids, attention_mask, entity_mask, tokenizer,
                             entity_prob=0.30, non_entity_prob=0.10):
    """
    Entity-aware masking: mask entity tokens at higher rate than non-entity.

    Reference: ENPAR (EACL 2021) masked entity prediction +
    TKRE (IJCAI 2025) differential masking probabilities.

    Args:
        input_ids: (B, T)
        attention_mask: (B, T)
        entity_mask: (B, T) — 1 where token belongs to predicted entity, 0 otherwise
        tokenizer: for special token ids
        entity_prob: mask probability for entity tokens
        non_entity_prob: mask probability for non-entity tokens
    Returns: same as mask_tokens.
    """
    orig_ids = input_ids.clone()

    # Build per-token mask probability
    prob_matrix = torch.where(
        entity_mask.bool(),
        torch.full_like(input_ids, entity_prob, dtype=torch.float),
        torch.full_like(input_ids, non_entity_prob, dtype=torch.float),
    )

    # Don't mask special tokens or padding
    special = (
        (input_ids == tokenizer.cls_token_id) |
        (input_ids == tokenizer.sep_token_id) |
        (input_ids == tokenizer.pad_token_id)
    )
    prob_matrix.masked_fill_(special, 0.0)
    prob_matrix.masked_fill_(~attention_mask.bool(), 0.0)

    mask_pos = torch.bernoulli(prob_matrix).bool()
    masked_ids = input_ids.clone()
    masked_ids[mask_pos] = tokenizer.mask_token_id

    return masked_ids, mask_pos, orig_ids


class EntityAwareDataset(torch.utils.data.Dataset):
    """Loads text + entity_token_mask from JSONL produced by generate_entity_masks.py."""

    def __init__(self, jsonl_path, tokenizer, max_length=128):
        self.tokenizer = tokenizer
        self.max_length = max_length
        with open(jsonl_path) as f:
            self.examples = [json.loads(line) for line in f]

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        ex = self.examples[idx]
        enc = self.tokenizer(
            ex["text"], truncation=True, max_length=self.max_length,
            padding=False, return_tensors=None,
        )
        # Truncate entity mask to match tokenizer output length
        entity_mask = ex["entity_token_mask"][:len(enc["input_ids"])]
        # Pad if shorter (shouldn't happen, but safety)
        while len(entity_mask) < len(enc["input_ids"]):
            entity_mask.append(0)
        return {
            "input_ids": enc["input_ids"],
            "attention_mask": enc["attention_mask"],
            "entity_mask": entity_mask,
        }


def collate_entity_aware(batch, pad_token_id=0):
    """Pad input_ids/attention_mask/entity_mask to max length in batch."""
    max_len = max(len(b["input_ids"]) for b in batch)
    B = len(batch)
    input_ids = torch.full((B, max_len), pad_token_id, dtype=torch.long)
    attention_mask = torch.zeros((B, max_len), dtype=torch.long)
    entity_mask = torch.zeros((B, max_len), dtype=torch.long)
    for i, b in enumerate(batch):
        L = len(b["input_ids"])
        input_ids[i, :L] = torch.tensor(b["input_ids"], dtype=torch.long)
        attention_mask[i, :L] = torch.tensor(b["attention_mask"], dtype=torch.long)
        entity_mask[i, :L] = torch.tensor(b["entity_mask"], dtype=torch.long)
    return {"input_ids": input_ids, "attention_mask": attention_mask, "entity_mask": entity_mask}


def build_entity_aware_loader(jsonl_path, tokenizer, batch_size=32, max_length=128):
    ds = EntityAwareDataset(jsonl_path, tokenizer, max_length)
    pad_id = tokenizer.pad_token_id
    return torch.utils.data.DataLoader(
        ds, batch_size=batch_size, shuffle=True, drop_last=True,
        collate_fn=lambda b: collate_entity_aware(b, pad_token_id=pad_id),
    )


def main():
    args = parse_args()

    print(f"=== ELECTRA Cooperative Pre-training ===")
    print(f"  model: {args.model_name}")
    entity_mode = bool(args.entity_mask_jsonl)
    mask_mode = "entity-aware" if entity_mode else ("span" if args.span_mask else "token")
    print(f"  gen_layers: {args.gen_layers}, mask_mode: {mask_mode}")
    if entity_mode:
        print(f"  entity_mask: {args.entity_mask_jsonl}")
        print(f"  entity_prob: {args.entity_mask_prob}, non_entity_prob: {args.non_entity_mask_prob}")
    else:
        print(f"  mask_prob: {args.mask_prob}")
    print(f"  lambda_disc: {args.lambda_disc}")
    print(f"  gen_lr: {args.gen_lr}, disc_lr: {args.disc_lr}")
    print(f"  steps: {args.max_steps}, batch: {args.batch_size}")

    # Seed
    random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)

    device = torch.device(args.device or ("cuda" if torch.cuda.is_available() else "cpu"))
    print(f"  device: {device}")

    # Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model_name)

    # Data: unlabeled arXiv text
    # Data: entity-aware JSONL or plain arXiv text
    if args.entity_mask_jsonl:
        data_loader = build_entity_aware_loader(
            args.entity_mask_jsonl, tokenizer,
            batch_size=args.batch_size, max_length=args.max_length,
        )
        print(f"  Entity-aware corpus: {len(data_loader.dataset)} documents from {args.entity_mask_jsonl}")
    else:
        data_loader = build_arxiv_loader(
            tokenizer, batch_size=args.batch_size, max_length=args.max_length,
        )
        print(f"  arXiv corpus: {len(data_loader.dataset)} documents")
    data_iter = cycle(data_loader)

    # --- Build models ---

    # Discriminator: full BertKGExtractor (same as fine-tuning target)
    # We include span NER heads so state_dict keys match at fine-tuning time.
    # These heads receive no gradients during pre-training.
    from data.scierc import NUM_BIO_TAGS, NUM_RELATIONS, ENTITY_TYPES
    disc = BertKGExtractor(
        args.model_name,
        num_bio_tags=NUM_BIO_TAGS,
        num_relations=NUM_RELATIONS,
        num_entity_types=len(ENTITY_TYPES),
        use_span_ner=True,
    ).to(device)

    # Generator: small SciBERT sharing embeddings with discriminator
    gen = SciBERTGenerator(disc.backbone, n_layers=args.gen_layers).to(device)

    # RTD head
    rtd_head = ReplacedTokenDetector(disc.backbone.hidden_size).to(device)

    # Count parameters
    shared_ids = {id(p) for p in disc.backbone.bert.embeddings.word_embeddings.parameters()}
    shared_ids |= {id(p) for p in disc.backbone.bert.embeddings.position_embeddings.parameters()}
    gen_new = sum(p.numel() for p in gen.parameters() if id(p) not in shared_ids)
    disc_total = sum(p.numel() for p in disc.parameters())
    rtd_total = sum(p.numel() for p in rtd_head.parameters())
    print(f"  disc params: {disc_total/1e6:.1f}M, gen new params: {gen_new/1e6:.1f}M, rtd: {rtd_total/1e3:.0f}K")

    # --- Optimizer with param groups ---
    shared_emb_params = (
        list(disc.backbone.bert.embeddings.word_embeddings.parameters()) +
        list(disc.backbone.bert.embeddings.position_embeddings.parameters())
    )

    gen_only_params = [p for p in gen.parameters() if id(p) not in shared_ids and p.requires_grad]
    disc_only_params = [p for p in disc.parameters() if id(p) not in shared_ids and p.requires_grad]

    optimizer = AdamW([
        {"params": shared_emb_params, "lr": args.disc_lr, "weight_decay": args.weight_decay},
        {"params": gen_only_params, "lr": args.gen_lr, "weight_decay": args.weight_decay},
        {"params": disc_only_params, "lr": args.disc_lr, "weight_decay": args.weight_decay},
        {"params": list(rtd_head.parameters()), "lr": args.disc_lr, "weight_decay": args.weight_decay},
    ])
    scheduler = get_linear_schedule_with_warmup(
        optimizer, num_warmup_steps=args.warmup_steps, num_training_steps=args.max_steps,
    )

    # --- Training loop ---
    gen.train()
    disc.train()
    rtd_head.train()

    t0 = time.time()
    best_rtd_acc = 0.0
    V = tokenizer.vocab_size

    for step in range(1, args.max_steps + 1):
        batch = next(data_iter)
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        # 1. Mask tokens (token-level or span-level)
        if args.entity_mask_jsonl:
            entity_mask = batch["entity_mask"].to(device)
            masked_ids, mask_pos, orig_ids = mask_tokens_entity_aware(
                input_ids, attention_mask, entity_mask, tokenizer,
                entity_prob=args.entity_mask_prob,
                non_entity_prob=args.non_entity_mask_prob,
            )
        else:
            mask_fn = mask_tokens_span if args.span_mask else mask_tokens
            masked_ids, mask_pos, orig_ids = mask_fn(
                input_ids, attention_mask, tokenizer, args.mask_prob,
            )
        n_masked = mask_pos.sum().item()
        if n_masked == 0:
            continue

        # 2. Generator: MLM on masked positions
        gen_logits = gen(masked_ids, attention_mask)  # (B, T, V)
        mlm_loss = F.cross_entropy(
            gen_logits[mask_pos],   # (n_masked, V)
            orig_ids[mask_pos],     # (n_masked,)
        )

        # 3. Sample replacements from generator (no grad for sampling)
        with torch.no_grad():
            gen_probs = F.softmax(gen_logits, dim=-1)  # (B, T, V)
            # Only sample at masked positions to save compute
            sampled_flat = torch.multinomial(
                gen_probs.view(-1, gen_probs.size(-1)), 1,
            ).view(input_ids.shape)  # (B, T)

        # 4. Build corrupted input
        corrupted_ids = input_ids.clone()
        corrupted_ids[mask_pos] = sampled_flat[mask_pos]

        # 5. Discriminator labels: 1 where token differs from original
        is_replaced = (corrupted_ids != input_ids).float()

        # Only compute loss on non-special, non-pad tokens
        special = (
            (input_ids == tokenizer.cls_token_id) |
            (input_ids == tokenizer.sep_token_id) |
            (input_ids == tokenizer.pad_token_id)
        )
        disc_mask = attention_mask.bool() & ~special

        # 6. Discriminator forward
        disc_hidden = disc.encode(
            modality="text", input_ids=corrupted_ids, attention_mask=attention_mask,
        )
        disc_logits = rtd_head(disc_hidden)  # (B, T)

        # Binary CE on all valid tokens
        disc_loss = F.binary_cross_entropy_with_logits(
            disc_logits[disc_mask],
            is_replaced[disc_mask],
        )

        # 7. Combined loss
        total_loss = mlm_loss + args.lambda_disc * disc_loss

        # 8. Backward + step
        optimizer.zero_grad()
        total_loss.backward()
        torch.nn.utils.clip_grad_norm_(
            list(gen.parameters()) + list(disc.parameters()) + list(rtd_head.parameters()),
            1.0,
        )
        optimizer.step()
        scheduler.step()

        # --- Logging ---
        if step % 10 == 0 or step == 1:
            with torch.no_grad():
                mlm_preds = gen_logits[mask_pos].argmax(dim=-1)
                mlm_acc = (mlm_preds == orig_ids[mask_pos]).float().mean().item()

                rtd_preds = (disc_logits[disc_mask] > 0).float()
                rtd_acc = (rtd_preds == is_replaced[disc_mask]).float().mean().item()

                replace_rate = is_replaced[disc_mask].mean().item()

            elapsed = time.time() - t0
            print(
                f"[step {step:5d}/{args.max_steps}] "
                f"loss={total_loss.item():.4f} "
                f"mlm={mlm_loss.item():.4f}(acc={mlm_acc:.3f}) "
                f"rtd={disc_loss.item():.4f}(acc={rtd_acc:.3f}) "
                f"repl={replace_rate:.3f} "
                f"({elapsed:.0f}s)"
            )

        # --- Eval / save ---
        if step % args.eval_every == 0 or step == args.max_steps:
            with torch.no_grad():
                mlm_preds = gen_logits[mask_pos].argmax(dim=-1)
                mlm_acc = (mlm_preds == orig_ids[mask_pos]).float().mean().item()
                rtd_preds = (disc_logits[disc_mask] > 0).float()
                rtd_acc = (rtd_preds == is_replaced[disc_mask]).float().mean().item()

            print(f"\n  [eval @ step {step}] mlm_acc={mlm_acc:.4f}, rtd_acc={rtd_acc:.4f}")

            save_path = Path(args.save_to)
            save_path.parent.mkdir(parents=True, exist_ok=True)
            torch.save({
                "discriminator": disc.state_dict(),
                "generator": gen.state_dict(),
                "rtd_head": rtd_head.state_dict(),
                "step": step,
                "mlm_acc": mlm_acc,
                "rtd_acc": rtd_acc,
                "args": vars(args),
            }, save_path)
            print(f"  Saved checkpoint to {save_path}")

            if rtd_acc > best_rtd_acc:
                best_rtd_acc = rtd_acc
                best_path = save_path.with_name(save_path.stem + "_best.pt")
                torch.save({
                    "discriminator": disc.state_dict(),
                    "step": step,
                    "mlm_acc": mlm_acc,
                    "rtd_acc": rtd_acc,
                    "args": vars(args),
                }, best_path)
                print(f"  Best RTD accuracy: {best_rtd_acc:.4f} → saved to {best_path}")
            print()

    elapsed = time.time() - t0
    print(f"\n=== Pre-training complete ===")
    print(f"  Total time: {elapsed:.0f}s ({elapsed/60:.1f}min)")
    print(f"  Best RTD accuracy: {best_rtd_acc:.4f}")
    print(f"  Checkpoint: {args.save_to}")
    print(f"  Next: fine-tune with train_span.py --pretrain-ckpt {args.save_to}")


if __name__ == "__main__":
    main()
